apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: ml-autoscaler-ml-autoscaler
  namespace: monitoring
  labels:
    release: mon
spec:
  selector:
    matchLabels:
      app: ml-autoscaler
  namespaceSelector:
    matchNames: ["thesis"]
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
