apiVersion: apps/v1
kind: Deployment
metadata:
  name: ml-autoscaler
  namespace: thesis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ml-autoscaler
  template:
    metadata:
      labels:
        app: ml-autoscaler
    spec:
      serviceAccountName: ml-autoscaler
      containers:
        - name: ml-autoscaler
          image: luca459/thesis:ml-autoscaler1.9.7
          env:
            - name: PROM_URL
              value: "http://prometheus-operated.monitoring.svc:9090"
            - name: IDLE_CAP_PODS
              value: "1"
          ports:
            - name: http
              containerPort: 8000
          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 30
            periodSeconds: 10
            failureThreshold: 3
