apiVersion: v1
kind: Service
metadata:
  name: ml-autoscaler
  namespace: thesis
  labels:
    app: ml-autoscaler
spec:
  ports:
  - name: http
    port: 80
    targetPort: 8000
  selector:
    app: ml-autoscaler
